### ISSUE TITLE
Pick a Dataset that can be generalized and add a model

### ISSUE THREAD

**Issue by ya332** [drexelai/binary-search-in-neural-nets#2]
MNIST, CIFAR-10

**Comment by ethanmoyer** [comment]
Maybe we only need a data set with two classes since that's the easiest classification to do.

**Comment by ya332** [comment]
Correct, though you can use MNIST or CIFAR-10 for a binary classification problem. Just pick one class label, lets say label is 4. So the binary classification problem that you are trying to solve is now to determine whether your prediction is 4 or not.

**Comment by isamu-isozaki** [comment]
I think the titanic dataset will be a good choice because it has 14 features and 1 output(survived not survived). It's quite a popular dataset that I did my first machine learning mini-project on.

**Comment by ya332** [comment]
Closed this issue after this PR #9.
