### ISSUE TITLE
Implement linear search (O(N)) 

### ISSUE THREAD

**Issue by ya332** [drexelai/binary-search-in-neural-nets#3]
Implement linear search (O(N)) # need to train the model N times.

**Comment by sd3536** [comment]
I can do this.

**Comment by ya332** [comment]
@sd3536 Invited to the repo with write access. Feel free to create a PR.

**Comment by a-augustin** [comment]
I’d like to work on this as well

**Comment by ya332** [comment]
@a-augustin invited to the repo with write access. Feel free to create a PR to contribute.

**Comment by ya332** [comment]
This is completed.
