### ISSUE TITLE
Determine trendline over two end points, determine the slope and determine side to get rid of

### ISSUE THREAD

**Issue by ya332** [drexelai/binary-search-in-neural-nets#4]
Given two endpoints, we need to be able to determine a trend(slope) between the endpoints and find a way to figure out which side to get rid of in your search. 
For example, below you see a red dot and a black dot on the right.  Once you know that the accuracy is going up from right to left, you know that the n values to the right of the dot pair can be ignored.
![image](https://user-images.githubusercontent.com/26026196/98317364-5a035000-1faa-11eb-80d8-9a7b597bf8a3.png)

**Comment by ethanmoyer** [comment]
I'd like to do this one!

**Comment by ya332** [comment]
Invited to the repo with write access. Feel free to create a PR and remove the `help wanted` label if you are okay working on it by yourself.

**Comment by a-augustin** [comment]
I can help out with this if still needed.

**Comment by ya332** [comment]
> I can help out with this if still needed.

This is a little bit complicated @a-augustin. For each accuracy point during binary search, you have to fit a normal distribution to see the point is 2 std greater than the normal distribution's mean to decide which side to get rid of. there are multiple steps required to do this. You can start small by creating a function to generate a normal distribution and then maybe another function that takes the previous distribution and a point to return left or right as output. Then finally, you can try to integrate these two functions to binary search in the pipeline. I would suggest watching all the YouTube recordings that I have posted in the channel if you still want to contribute.

**Comment by ya332** [comment]
Closing this.
