### ISSUE TITLE
Find the maximum/minumum value in a partially sorted array

### ISSUE THREAD

**Issue by ya332** [drexelai/binary-search-in-neural-nets#5]
We need a piece of code/algorithm to find the maximum/minimum value in the accuracy plot below.  
![image](https://user-images.githubusercontent.com/26026196/98317547-b0708e80-1faa-11eb-9b79-c2422945835b.png)

**Comment by a-augustin** [comment]
I can do this one.

**Comment by ya332** [comment]
We have binary search and linear search for now. We can reopen this issue later.
