### ISSUE TITLE
Adapt the code so that user can pass n as input and run the entire pipeline (train + test + save) 

### ISSUE THREAD

**Issue by ya332** [drexelai/binary-search-in-neural-nets#6]
We need to make a script that set ups a pipeline for train/test/result phase of a script.
Imagine you have a script train.py and a test.py. Goal is to create a run.pr or something similar that can call the train.py and test.py scripts and save/plot the results.

**Comment by isamu-isozaki** [comment]
I want to be assigned t this. I don't have permissions but can someone add me?

**Comment by ya332** [comment]
Invited to the repo with write access. Feel free to create a PR.

**Comment by isamu-isozaki** [comment]
thanks

**Comment by adunlop621** [comment]
I'd like to work on this as well. How do I add myself?

**Comment by ya332** [comment]
Invited to the repo with write access. Feel free to create a PR.

**Comment by ya332** [comment]
The issue is closed we added the pipeline.
